language: python

python:
  - "3.6"

services:
  - docker

env:
  - IMAGE=kazakovdu/blog

_deploy_if: &deploy_condition
  if: branch = master AND \
      tag IS present

jobs:
  include:
    - stage: test
      name: "Run unit tests"
      install: pip install -r requirements/test.txt
      before_script: cp example.secrets .secrets
      script: make test

    - stage: build
      name: "Build a docker image"
      before_script: chmod +x deploy/entrypoint.sh
      script: docker build -t $IMAGE:$TRAVIS_TAG .

#    - stage: push
#      name: "Push an image to Docker Hub"
#      *deploy_condition
#      before_script:
#        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#      script: docker push $IMAGE:$TRAVIS_TAG

    - stage: update
      name: "Update the app on the server"
#      *deploy_condition
      before_script:
        - echo -e $SSH_KEY | sed 's/\$ /\n/g' > ssh_key
        - chmod 600 ssh_key
        - ssh -i ssh_key -o "StrictHostKeyChecking=no" -p $SSH_PORT $SSH_TARGET
      script: echo "travis via ssh" > hello
#      script: ./update.sh
