language: python

python:
  - "3.6"

services:
  - docker

env:
  - IMAGE=kazakovdu/blog

install: pip install -r requirements/test.txt

before_script: cp example.secrets .secrets

script: make test

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - chmod +x deploy/entrypoint.sh
    - docker build -t $IMAGE:$TRAVIS_TAG .

deploy:
  provider: script
  script: docker push $IMAGE:$TRAVIS_TAG
  on:
    tags: true
