language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - IMAGE=kazakovdu/blog
    - TAG=${TRAVIS_TAG:-1}
    - HOST_CHECK="StrictHostKeyChecking=no"

jobs:
  include:
    - stage: test
      name: "Run unit tests"
      install: pip install -r requirements/test.txt
      before_script: cp example.secrets .secrets
      script: make test

    - stage: build
      name: "Build a docker image"
      install: skip
      before_script: chmod +x deploy/entrypoint.sh
      script: docker build -t $IMAGE:$TAG .

    - stage: build & push
      name: "Build and push an image to Docker Hub"
      install: skip
      before_script:
        - chmod +x deploy/entrypoint.sh
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      script:
        - docker build -t $IMAGE:$TAG .
        - docker push $IMAGE:$TAG

    - stage: update
      name: "Update the app on the server"
      install: skip
      before_script:
        - echo -e $SSH_KEY | sed 's/\$ /\n/g' > ssh_key
        - chmod 600 ssh_key
        - chmod +x deploy/update.sh
      script:
        - ssh -i ssh_key -o $HOST_CHECK -p $SSH_PORT $SSH_TARGET "bash -s" < deploy/update.sh

stages:
  - test
  - name: build
    if: tag IS blank
  - name: build & push
    if: tag IS present
  - name: update
    if: tag IS present
