version: '2'
services:
  blog:
    build: .
    container_name: blog
    command: make prod
    environment:
      - DOMAIN=$DOMAIN
    restart: always
    volumes:
      - /var/run/postgresql:/run/postgresql
      - $PWD/.secrets:/www/.secrets
      - $PWD/volumes/log:/www/log
      - $PWD/volumes/public:/www/public/volume
    ports:
      - "8000:8000"
